# This playbook will check if the partition have enough space, otherwise it will resize them, after that it will install Docker

- name: Install Docker on the centOS group machine
  hosts: centOs
  become_user: root
  become: true

  vars_files:
    - ./group_vars/all.yml

  roles:
    # Check if the disk have enough space
    - role: check_disk
      tags: [ setup ]

    # Install Docker
    - role: geerlingguy.docker
      tags: [ docker ]
